# Generated by Django 5.0 on 2023-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
